### ISSUE TITLE
Deploy won't work

### ISSUE THREAD

**Issue by AeroChangmin** [SNUArduinoLabs/coe_client#27]
When I update and deploy a schedule that a client has, it won't work

**Comment by cacyss0807** [comment]
@AeroChangmin can you be a little more specific. 

- It does not get updated?
- There is a black screen?

What does "it won't work" means in this case?

**Comment by AeroChangmin** [comment]
First one. Client keep playing the same schedule

**Comment by cacyss0807** [comment]
Oh! okay I will check and get back to you. Thank you.
Also, could you send me the logs.

**Comment by cacyss0807** [comment]
Also, are you editing the currently being played schedule or trying to play a new schedule?

**Comment by AeroChangmin** [comment]
Here

2015-08-31 12:40:56,161 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:41:56,167 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:41:56,177 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:41:56,225 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:42:56,278 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:42:56,288 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:42:56,340 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:43:56,344 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:43:56,354 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:43:56,403 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:44:56,464 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:44:56,472 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:44:56,515 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:45:56,518 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:45:56,527 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:45:56,590 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:46:56,651 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:46:56,661 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:46:56,709 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:47:56,770 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:47:56,780 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:47:56,831 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:48:56,836 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:48:56,847 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:48:56,898 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:49:56,915 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:49:56,924 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:49:56,972 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:50:56,976 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:50:56,985 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:50:57,034 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:51:57,090 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:51:57,100 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:51:57,152 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:52:57,175 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:52:57,184 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:52:57,234 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:53:57,295 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:53:57,306 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:53:57,356 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:54:57,382 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:54:57,391 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:54:57,442 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:55:57,445 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:55:57,455 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:55:57,504 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:56:57,563 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:56:57,572 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:56:57,621 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:57:57,629 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:57:57,638 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:57:57,690 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:58:57,748 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:58:57,757 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:58:57,807 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 12:59:57,842 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 12:59:57,850 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 12:59:57,893 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:00:57,954 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:00:57,963 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:00:58,015 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:01:58,070 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:01:58,080 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:01:58,131 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:02:58,190 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:02:58,199 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:02:58,248 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:03:58,309 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:03:58,319 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:03:58,370 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:04:58,431 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:04:58,439 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:04:58,483 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:05:58,544 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:05:58,554 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:05:58,603 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:06:58,615 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:06:58,627 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:06:58,680 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:07:58,696 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:07:58,705 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:07:58,754 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:08:58,815 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:08:58,825 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:08:58,875 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:09:58,912 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:09:58,922 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:09:58,973 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:10:59,034 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:10:59,044 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:10:59,092 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:11:59,095 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:11:59,104 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:11:59,153 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:12:59,199 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:12:59,209 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:12:59,261 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
2015-08-31 13:13:59,290 [player.py : 57 ] DEBUG - Getting schedule to play...
2015-08-31 13:13:59,299 [player.py : 62 ] DEBUG - Getting schedule for the next 5 minutes...
2015-08-31 13:13:59,347 [player.py : 113] DEBUG - No NEW schedule to play. Check again in 60 second(s)
Webapp
2015-08-31 13:00:24,536 [db_manager.py : 157] INFO - File [2f5b29874ccc8f4a26601ba261ee31e48e95080a]'s metadata successfully stored in the database (23.23 ms)
Exception in thread sched_save_thread:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/pi/coe_client/src/db_manager.py", line 154, in save_sched_to_db
file_sched.insert(dict(schedule_id=self.curr_sched_id, file_id=curr_file_id, play_order=plo))
File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/table.py", line 73, in insert
res = self.database.executable.execute(self.table.insert(row))
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) columns schedule_id, file_id are not unique [SQL: u'INSERT INTO file_sched (schedule_id, file_id, play_order) VALUES (?, ?, ?)'] [parameters: (7, 2, 2)]
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:66]:
sched_save_thread finished within timeout time of 5 seconds.
--------------------------------------------------------------------------------
2015-08-31 13:00:24,614 [webserver.py : 66 ] INFO - sched_save_thread finished within timeout time of 5 seconds.
2015-08-31 13:00:24,616 [_internal.py : 87 ] INFO - 192.168.0.35 - - [31/Aug/2015 13:00:24] "POST /schedule HTTP/1.1" 200 -
2015-08-31 13:04:48,584 [_internal.py : 87 ] INFO - 192.168.0.35 - - [31/Aug/2015 13:04:48] "GET /status?numOfLines=100,100,100 HTTP/1.1" 200 -
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:41]:
Start of get_json
--------------------------------------------------------------------------------
2015-08-31 13:06:09,444 [webserver.py : 41 ] INFO - Start of get_json
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:44]:
Request Json
--------------------------------------------------------------------------------
2015-08-31 13:06:09,448 [webserver.py : 44 ] INFO - Request Json
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:45]:
{u'priority': 0, u'start_datetime': u'2015-08-31 08:00:00', u'schedule_name': u'a', u'days_of_week': [u'MON', u'TUE', u'WED', u'THU', u'FRI'], u'schedule_desc': u'sa', u'schedule_id': 7, u'end_datetime': u'2015-08-31 20:00:00', u'content_files': [{u'path': u'/home/test/coe_control_center/webapp/public/uploads/content/file/8/2f5b29874ccc8f4a26601ba261ee31e48e95080a', u'play_order': 1, u'type': u'VIDEO', u'interval': u'1', u'filename': u'2f5b29874ccc8f4a26601ba261ee31e48e95080a'}, {u'path': u'/home/test/coe_control_center/webapp/public/uploads/content/file/10/7afa22f979afd667591968f99dfb91e562f47b42', u'play_order': 2, u'type': u'VIDEO', u'interval': u'4', u'filename': u'7afa22f979afd667591968f99dfb91e562f47b42'}], u'action': u'add', u'marquee_text': u''}
--------------------------------------------------------------------------------
2015-08-31 13:06:09,448 [webserver.py : 45 ] INFO - {u'priority': 0, u'start_datetime': u'2015-08-31 08:00:00', u'schedule_name': u'a', u'days_of_week': [u'MON', u'TUE', u'WED', u'THU', u'FRI'], u'schedule_desc': u'sa', u'schedule_id': 7, u'end_datetime': u'2015-08-31 20:00:00', u'content_files': [{u'path': u'/home/test/coe_control_center/webapp/public/uploads/content/file/8/2f5b29874ccc8f4a26601ba261ee31e48e95080a', u'play_order': 1, u'type': u'VIDEO', u'interval': u'1', u'filename': u'2f5b29874ccc8f4a26601ba261ee31e48e95080a'}, {u'path': u'/home/test/coe_control_center/webapp/public/uploads/content/file/10/7afa22f979afd667591968f99dfb91e562f47b42', u'play_order': 2, u'type': u'VIDEO', u'interval': u'4', u'filename': u'7afa22f979afd667591968f99dfb91e562f47b42'}], u'action': u'add', u'marquee_text': u''}
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:53]:
Trying to create thread to save JSON to db.
--------------------------------------------------------------------------------
2015-08-31 13:06:09,450 [webserver.py : 53 ] INFO - Trying to create thread to save JSON to db.
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:58]:
sched_save_thread created. Starting it.
--------------------------------------------------------------------------------
2015-08-31 13:06:09,451 [webserver.py : 58 ] INFO - sched_save_thread created. Starting it.
2015-08-31 13:06:09,453 [db_manager.py : 73 ] INFO - Trying to save JSON (schedule) into the database.
2015-08-31 13:06:09,457 [db_manager.py : 82 ] INFO - Parsing JSON for [7] schedule...
2015-08-31 13:06:09,459 [db_manager.py : 91 ] INFO - Requested to save schedule [7] in the database.
2015-08-31 13:06:09,487 [db_manager.py : 101] INFO - The schedule [7] already exists. Removing it from database.
--------------------------------------------------------------------------------
INFO in webserver [/home/pi/coe_client/src/webserver.py:66]:
sched_save_thread finished within timeout time of 5 seconds.
--------------------------------------------------------------------------------
2015-08-31 13:06:14,455 [webserver.py : 66 ] INFO - sched_save_thread finished within timeout time of 5 seconds.
2015-08-31 13:06:14,457 [_internal.py : 87 ] INFO - 192.168.0.35 - - [31/Aug/2015 13:06:14] "POST /schedule HTTP/1.1" 200 -
Exception in thread sched_save_thread:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/pi/coe_client/src/db_manager.py", line 102, in save_sched_to_db
sched_table.delete(id=self.curr_sched_id)
File "/usr/local/lib/python2.7/dist-packages/dataset/persistence/table.py", line 200, in delete
rows = self.database.executable.execute(stmt)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
context)
File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'DELETE FROM schedule WHERE schedule.id = ?'] [parameters: (7,)]
2015-08-31 13:09:48,826 [_internal.py : 87 ] INFO - 192.168.0.35 - - [31/Aug/2015 13:09:48] "GET /status?numOfLines=100,100,100 HTTP/1.1" 200 -
Downloader
2015-08-31 13:12:02,698 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:07,704 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:07,717 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:07,718 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:12,724 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:12,736 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:12,737 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:17,743 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:17,756 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:17,757 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:22,763 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:22,776 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:22,777 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:27,783 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:27,796 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:27,798 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:32,804 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:32,820 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:32,822 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:37,828 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:37,841 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:37,842 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:42,848 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:42,861 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:42,862 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:47,868 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:47,881 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:47,882 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:52,888 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:52,901 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:52,902 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:12:57,908 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:12:57,921 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:12:57,922 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:02,928 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:02,941 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:02,942 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:07,948 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:07,961 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:07,962 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:12,968 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:12,981 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:12,982 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:17,988 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:18,002 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:18,003 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:23,008 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:23,021 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:23,022 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:28,025 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:28,039 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:28,041 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:33,044 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:33,058 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:33,059 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:38,065 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:38,077 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:38,078 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:43,084 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:43,097 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:43,098 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:48,104 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:48,116 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:48,117 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:53,122 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:53,134 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:53,135 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:13:58,140 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:13:58,153 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:13:58,154 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:03,160 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:03,174 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:03,175 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:08,177 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:08,190 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:08,191 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:13,197 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:13,211 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:13,213 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:18,218 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:18,232 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:18,233 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:23,239 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:23,253 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:23,254 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:28,260 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:28,274 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:28,275 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:33,280 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:33,293 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:33,294 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:38,300 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:38,313 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:38,314 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:43,320 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:43,335 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:43,336 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0
2015-08-31 13:14:48,341 [downloader.py : 129] DEBUG - Getting list of files to download...
2015-08-31 13:14:48,353 [downloader.py : 131] INFO - Files to download: []
2015-08-31 13:14:48,354 [downloader.py : 134] DEBUG - No files to download. Waiting for 5.0

**Comment by cacyss0807** [comment]
@AeroChangmin we checked and tested it and it seems that it has been fixed. 

The problem was that when trying to insert multiple equal files, this blocked the database because of a unique key error. Anyhow, it has been fixed now.
